gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#947CFF"
      - "bold"
    inactiveBorderColor:
      - "#1793D1"
    searchingActiveBorderColor:
      - "#FFAA66"
      - "bold"
    optionsTextColor:
      - "#1793D1"
    selectedLineBgColor:
      - "#283457"
    cherryPickedCommitFgColor:
      - "#7898C7"
    cherryPickedCommitBgColor:
      - "#947CFF"
    markedBaseCommitFgColor:
      - "#7898C7"
    markedBaseCommitBgColor:
      - "#FFAA66"
    unstagedChangesColor:
      - "#FF6B6B"
    defaultFgColor:
      - "#7898C7"
