gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - magenta
      - "bold"
    inactiveBorderColor:
      - cyan
    searchingActiveBorderColor:
      - yellow
      - "bold"
    optionsTextColor:
      - magenta
    selectedLineBgColor:
      - default
    inactiveViewSelectedLineBgColor:
      - "#7898C7"
    cherryPickedCommitFgColor:
      - green
    cherryPickedCommitBgColor:
      - "#7898C7"
    markedBaseCommitFgColor:
      - cyan
    markedBaseCommitBgColor:
      - "#7898C7"
    unstagedChangesColor:
      - red
    defaultFgColor:
      - "#7898C7"
