[colors.primary]
background = "#07060E"
foreground = "#7898C7"

[colors.cursor]
text = "#07060E"
cursor = "#00B7EB"

[colors.selection]
background = "#283457"
text = "#00B7EB"

[colors.normal]
black = "#1c1e28"   # color0
red = "#FF6B6B"     # color1
green = "#8CCF7E"   # color2
yellow = "#FFD580"  # color3
blue = "#5CAEFF"    # color4
magenta = "#947CFF" # color5
cyan = "#00B7EB"    # color6
white = "#c0caf5"   # color7

[colors.bright]
black = "#3A3E52"   # color8
red = "#FF8787"     # color9
green = "#A7F3A1"   # color10
yellow = "#FFEAA7"  # color11
blue = "#A0CFFF"    # color12
magenta = "#E178FF" # color13
cyan = "#00E5FF"    # color14
white = "#f0f4ff"   # color15
