
[[mgr.prepend_keymap]]
on = "<C-x>"
run = ["plugin copy-file-contents"]
desc = "Copy contents of file"

[[mgr.prepend_keymap]]
on = ["<"]
run = "plugin relative-motions"
desc = "Trigger a new relative motion"

[[mgr.prepend_keymap]]
on = ["c", "a", "t"]
run = "plugin compress 'tar rpf'"
desc = "Archive selected files to tar"

[[mgr.prepend_keymap]]
on = ["c", "a", "a"]
run = "plugin compress"
desc = "Archive selected files"

[[mgr.prepend_keymap]]
on = ["c", "a", "p"]
run = "plugin compress -p"
desc = "Archive selected files (password)"

[[mgr.prepend_keymap]]
on = ["c", "a", "h"]
run = "plugin compress -ph"
desc = "Archive selected files (password+header)"

[[mgr.prepend_keymap]]
on = ["c", "a", "l"]
run = "plugin compress -l"
desc = "Archive selected files (compression level)"

[[mgr.prepend_keymap]]
on = ["c", "a", "u"]
run = "plugin compress -phl"
desc = "Archive selected files (password+header+level)"

[[mgr.prepend_keymap]]
on = ["<C-c>"]
run = "plugin close-and-restore-tab close_to_left"
desc = "Close the current tab and turn to right tab, or quit if it is last tab"

[[mgr.prepend_keymap]]
on = ["<C-t>"]
run = "plugin close-and-restore-tab restore"
desc = "Restore the closed tab"

[[mgr.prepend_keymap]]
# First Non-directory
on = ["g", "f", "f"]
run = "plugin first-non-directory"
desc = "Jumps to the first file"

[[mgr.prepend_keymap]]
# Chmod on howered files
on = ["m", "c"]
run = "plugin chmod"
desc = "Chmod on selected files"

[[mgr.prepend_keymap]]
on = ["b", "a"]
run = "plugin bookmarks save"
desc = "Save current position as a bookmark"

[[mgr.prepend_keymap]]
on = ["b", "j"]
run = "plugin bookmarks jump"
desc = "Jump to a bookmark"

[[mgr.prepend_keymap]]
on = ["b", "d"]
run = "plugin bookmarks delete"
desc = "Delete a bookmark"

[[mgr.prepend_keymap]]
on = ["b", "D"]
run = "plugin bookmarks delete_all"
desc = "Delete all bookmarks"

[[mgr.prepend_keymap]]
# Sudo 
on = ["R", "p", "p"]
run = "plugin sudo -- paste"
desc = "sudo paste"

[[mgr.prepend_keymap]]
on = ["R", "P"]
run = "plugin sudo -- paste --force"
desc = "sudo paste"

[[mgr.prepend_keymap]]
on = ["R", "r"]
run = "plugin sudo -- rename"
desc = "sudo rename"

[[mgr.prepend_keymap]]
on = ["R", "p", "l"]
run = "plugin sudo -- link"
desc = "sudo link"

[[mgr.prepend_keymap]]
on = ["R", "p", "r"]
run = "plugin sudo -- link --relative"
desc = "sudo link relative path"

[[mgr.prepend_keymap]]
on = ["R", "p", "L"]
run = "plugin sudo -- hardlink"
desc = "sudo hardlink"

[[mgr.prepend_keymap]]
on = ["R", "a"]
run = "plugin sudo -- create"
desc = "sudo create"

[[mgr.prepend_keymap]]
on = ["R", "d"]
run = "plugin sudo -- remove"
desc = "sudo trash"

[[mgr.prepend_keymap]]
on = ["R", "D"]
run = "plugin sudo -- remove --permanently"
desc = "sudo delete"

[[mgr.prepend_keymap]]
# Wl-Clipboard
on = "<C-y>"
run = "plugin wl-clipboard"

####################################################
#############      Navgigation      ################
####################################################

# Goto:

[[mgr.prepend_keymap]]
on = ["g", "f", "l"]
run = "follow"
desc = "Follow hovered symlink"

[[mgr.prepend_keymap]]
on = ["g", "/"]
run = "cd /"
desc = "Goto Root"

[[mgr.prepend_keymap]]
on = ["g", "h"]
run = "cd $HOME"
desc = "Goto Home"

[[mgr.prepend_keymap]]
on = ["g", "c"]
run = "cd ~/.config"
desc = "Goto Config-files"

[[mgr.prepend_keymap]]
on = ["g", "d", "p"]
run = "cd ~/Dev/projects"
desc = "Goto Projects"

[[mgr.prepend_keymap]]
on = ["g", "d", "r"]
run = "cd ~/Dev/res"
desc = "Goto Resources"

[[mgr.prepend_keymap]]
on = ["g", "d", "e"]
run = "cd ~/Dev/res/repos"
desc = "Goto My Repos"

[[mgr.prepend_keymap]]
on = ["g", "d", "w"]
run = "cd ~/Downloads"
desc = "Goto Downloads"

[[mgr.prepend_keymap]]
on = ["g", "d", "o"]
run = "cd ~/dotfiles"
desc = "Goto Dotfiles"

[[mgr.prepend_keymap]]
on = ["g", "m"]
run = "cd ~/myStuff"
desc = "Goto My Stuff"

[[mgr.prepend_keymap]]
on = ["g", "t"]
run = "cd ~/.local/share/Trash/files"
desc = "Goto Trash"

[[mgr.prepend_keymap]]
on = ["g", "l"]
run = "cd ~/.local"
desc = "Goto Locale Config"

[[mgr.prepend_keymap]]
on = ["g", "u"]
run = "cd /run/media/ricky"
desc = "Goto USB Mountpoint"

[[mgr.prepend_keymap]]
on = ["g", "m", "b"]
run = "cd /$HOME/myStuff/Documents/Bachata-Novalis"
desc = "Goto Bachata-Novalis"

[[mgr.prepend_keymap]]
on = ["g", "d", "v"]
run = "cd /$HOME/Dev"
desc = "Goto Dev"

[[mgr.prepend_keymap]]
on = ["g", "<Space>"]
run = "cd --interactive"
desc = "Jump interactively"

####################################################
#############      Yazi UI      ####################
####################################################

# Lazygit
[[mgr.prepend_keymap]]
on = ["u", "g"]
run = "plugin lazygit"
desc = "run lazygit"

# Trash Restore
[[mgr.prepend_keymap]]
on = ["u", "t", "f"]
run = "plugin restore"
desc = "Restore deleted files/folders"

[[mgr.prepend_keymap]]
on = ["u", "t", "i"]
run = "shell --block -- clear && trash-restore"
desc = "Restore deleted file (Interactive)"

# TODO: run = "shell --block -- clear && trash-restore --overwrite" --> merge instead of overwrite?

# Toggle Pane
[[mgr.prepend_keymap]]
on = ["u", "p"]
run = "plugin toggle-pane min-preview"
desc = "Toggle preview pane"
