general.import = ["~/.config/alacritty/themes/themes/electric-midnight.toml"]

[env]
WINIT_X11_SCALE_FACTOR = "1.0"
TERM = "xterm-256color"

[terminal.shell]
program = "/usr/bin/zsh"
args = ["--login"]

[window]
dimensions = { columns = 150, lines = 34 }
position = { x = 50, y = 80 }
padding = { x = 15, y = 20 }
decorations = "None"
resize_increments = true
opacity = 0.7
blur = true
option_as_alt = "Both"

[font]
normal = { family = "MesloLGS NF", style = "regular" }
size = 15
offset = { x = 0, y = 0 }

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "underline", blinking = "On" }
blink_interval = 500
unfocused_hollow = true

[keyboard]
bindings = [
  { key = "n", mods = "Control|Alt", action = "CreateNewWindow" },
  { key = "c", mods = "Control|Shift", action = "CopySelection" },
  { key = "v", mods = "Control|Shift", action = "PasteSelection" },
  { key = "q", mods = "Control|Alt", action = "Quit" },
  { key = "f", mods = "Control|Alt", action = "ToggleFullscreen" },
  { key = "m", mods = "Control|Alt", action = "Minimize" },
  { key = "t", mods = "Control|Shift", action = "CreateNewTab" },
]
