[colors]
ansi = [
  '#1c1e28',
  '#FF6B6B',
  '#8CCF7E',
  '#FFD580',
  '#5CAEFF',
  '#947CFF',
  '#00B7EB',
  '#c0caf5',
]
background = '#07060E'
brights = [
  '#3A3E52',
  '#FF8787',
  '#A7F3A1',
  '#FFEAA7',
  '#A0CFFF',
  '#E178FF',
  '#00E5FF',
  '#f0f4ff',
]
cursor_bg = '#00B7EB'
cursor_border = '#8b8198'
cursor_fg = '#07060E'
foreground = '#7898C7'
selection_bg = '#283457'
selection_fg = '#00B7EB'

[colors.indexed]

[metadata]
author = 'ricky'
name = 'ElectricMidnight'
