[mgr]
cwd = { fg = "cyan", italic = true }

# Hovered
hovered = { bg = "darkgrey" }
preview_hovered = { bg = "darkgrey" }
# hovered = { reversed = true }
# preview_hovered = { reversed = true }

# Find
find_keyword = { fg = "lightmagenta", bold = true }
find_position = { fg = "lightmagenta", bold = true }

# Marker
marker_copied = { fg = "green", bg = "green" }
marker_cut = { fg = "red", bg = "red" }
marker_marked = { fg = "magenta", bg = "magenta" }
marker_selected = { fg = "white", bg = "white" }

# Count
count_copied = { fg = "black", bg = "cyan" }
count_cut = { fg = "black", bg = "red" }
count_selected = { fg = "black", bg = "white" }

# Border
border_symbol = "│"
border_style = { fg = "grey" }
syntect_theme = "~/.config/yazi/flavors/icenode.yazi/tmtheme.xml"

[tabs]
active = { fg = "black", bg = "lightcyan" }
inactive = { fg = "lightcyan", bg = "black" }
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }

[mode]
normal_main = { fg = "green", bg = "black", bold = true }
normal_alt = { fg = "green", bg = "black" }
select_main = { fg = "black", bg = "magenta", bold = true }
select_alt = { fg = "magenta", bg = "grey" }

unset_main = { fg = "black", bg = "red", bold = true }
unset_alt = { fg = "red", bg = "grey" }

[status]
sep_left = { open = "", close = "" }
sep_right = { open = "", close = "" }
overall = { fg = "cyan", bg = "black" }

progress_label = { fg = "black", bold = true }
progress_normal = { fg = "cyan" }
progress_error = { fg = "red" }

perm_type = { fg = "lightcyan" }
perm_read = { fg = "cyan" }
perm_write = { fg = "yellow" }
perm_exec = { fg = "red" }
perm_sep = { fg = "lightcyan" }

[pick]
border = { fg = "#00baff" }
title = { fg = "magenta" }
active = { fg = "lightmagenta" }
inactive = { fg = "darkgrey" }

[input]
border = { fg = "#00baff" }
title = { fg = "lightmagenta" }
value = { fg = "grey" }

[completion]
border = { fg = "#00baff" }
title = { fg = "magenta" }
active = { fg = "lightmagenta" }
inactive = { fg = "darkgrey" }

icon_file = ""
icon_folder = ""
icon_command = ""

[tasks]
border = { fg = "lightcyan" }
title = { fg = "lightcyan" }
hovered = { fg = "grey", bg = "yellow" }

[which]
cols = 3
mask = { bg = "darkgrey" }
cand = { fg = "lightcyan" }
rest = { fg = "blue" }
desc = { fg = "grey" }
separator = " ➜ "
separator_style = { fg = "lightmagenta" }

[confirm]
border = { fg = "lightcyan" }
title = { fg = "lightcyan" }
content = { fg = "grey", italic = false }
list = { fg = "grey", italic = false }
btn_yes = { bg = "red", fg = "black", bold = true }
btn_no = { bg = "lightcyan", fg = "black", bold = true }
btn_labels = ["  [Y]es  ", "  (N)o  "]

[spot]
border = { fg = "lightcyan" }
title = { fg = "lightcyan" }

[notify]
title_info = { fg = "green" }
title_warn = { fg = "yellow" }
title_error = { fg = "red" }

icon_error = ""
icon_warn = ""
icon_info = ""

[help]
on = { fg = "cyan" }
run = { fg = "magenta" }
hovered = { bg = "darkgrey" }
footer = { fg = "grey", bg = "black" }

[filetype]
rules = [
  { mime = "image/*", fg = "cyan" },
  { mime = "{audio,video}/*", fg = "yellow" },
  { mime = "application/*zip", fg = "red" },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "red" },
  { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "grey" },

  # Empty files
  { mime = "inode/x-empty", fg = "red" },

  # Special files
  { name = "*", is = "orphan", fg = "red" },
  { name = "*", is = "exec", fg = "magenta" },

  # Fallback
  { name = "*/", fg = "cyan" },
]
